#!/usr/bin/env sh
set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

show_help() {
  echo "
    Usage: path/to/ffc-pay-core [OPTION...]
    Build payment services.
    Options:
      -h, --help       display this help text
    "
}

while :; do
  case $1 in
    -h|--help)   # Call a "show_help" function to display a synopsis, then exit.
      show_help
      exit
      ;;
    *)
      break
  esac

  shift
done

cd "${projectRoot}"
cd ./ffc-ahwr-farmer-apply && \
  docker-compose build
cd "${projectRoot}"
cd ./ffc-ahwr-farmer-claim && \
  docker-compose build
cd "${projectRoot}"
cd ./ffc-ahwr-application && \
  docker-compose build
cd "${projectRoot}"
cd ./ffc-ahwr-backoffice && \
  docker-compose build