#!/usr/bin/env sh
set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

show_help() {
  echo "
    Usage: path/to/ffc-ahwr-core [OPTION...]
    Open vet vists services in VS Code.
    Options:
      -f, --functions   include Azure Function Apps
      -h, --help       display this help text
    "
}

while :; do
  case $1 in
    -f|--functions)
      functions="true"
      ;;
    -h|--help)   # Call a "show_help" function to display a synopsis, then exit.
      show_help
      exit
      ;;
    *)
      break
  esac

  shift
done

cd "${projectRoot}"
  code ./ffc-ahwr-farmer-apply;
  code ./ffc-ahwr-farmer-claim;
  code ./ffc-ahwr-application;
  code ./ffc-ahwr-backoffice;


if [ "${functions}" = "true" ]; then
  code ./ffc-ahwr-event;
fi