#!/usr/bin/env sh
if [ -z "$(docker network ls --filter name=^ffc-ahwr$ --format={{.Name}})" ]; then
  echo "Creating ffc-ahwr Docker network"
  docker network create ffc-ahwr
fi

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

show_help() {
  echo "
    Usage: path/to/ffc-ahwr-core [OPTION...]
    Run vet vists services.
    Options:
      -f, --functions   include Azure Function Apps
      -h, --help       display this help text
    "
}

while :; do
  case $1 in
     -f|--functions)
      functions="true"
      ;;
    -h|--help)   # Call a "show_help" function to display a synopsis, then exit.
      show_help
      exit
      ;;
    *)
      break
  esac

  shift
done

cd "${projectRoot}"
  ./ffc-ahwr-farmer-apply/scripts/start -d;
  ./ffc-ahwr-farmer-claim/scripts/start -d;
  ./ffc-ahwr-application/scripts/start -d;
  ./ffc-ahwr-backoffice/scripts/start -d;


if [ "${functions}" = "true" ]; then
  ./ffc-ahwr-event/scripts/start -d;
fi